"""
Email notification utility (bots/email_notify.py)
Sends article content to configured email after writing.
Uses Python smtplib with SMTP server configured in .env.
"""
import logging
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger(__name__)

# Defaults
DEFAULT_RECIPIENT = ""


def send_article_email(article: dict, recipient: str | None = None) -> bool:
    """
    Send a written article via email.

    Required .env variables:
        SMTP_HOST     — SMTP server (e.g. smtp.gmail.com)
        SMTP_PORT     — SMTP port (default 587)
        SMTP_USER     — sender email address
        SMTP_PASSWORD — sender email password or app password

    Optional .env variables:
        EMAIL_RECIPIENT — default recipient (overridden by argument)

    Returns True on success, False on failure.
    """
    smtp_host = os.getenv("SMTP_HOST", "")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER", "")
    smtp_password = os.getenv("SMTP_PASSWORD", "")
    recipient = recipient or os.getenv("EMAIL_RECIPIENT", DEFAULT_RECIPIENT)

    if not recipient:
        logger.warning("Email recipient not configured (EMAIL_RECIPIENT missing). Skipping.")
        return False

    if not all([smtp_host, smtp_user, smtp_password]):
        logger.warning(
            "Email not configured (SMTP_HOST/SMTP_USER/SMTP_PASSWORD missing). "
            "Skipping email notification."
        )
        return False

    title = article.get("title", "(no title)")
    corner = article.get("corner", "")
    body = article.get("body", "")
    slug = article.get("slug", "")
    created_at = article.get("created_at", "")
    key_points = article.get("key_points", [])
    tags = article.get("tags", [])
    quality_issues = article.get("quality_issues", [])

    # Build key points HTML
    kp_html = ""
    if key_points:
        kp_items = "".join(f"<li>{kp}</li>" for kp in key_points)
        kp_html = f"<h3>Key Points</h3><ul>{kp_items}</ul>"

    # Build quality warnings
    qa_html = ""
    if quality_issues:
        qa_items = "".join(f"<li>{qi}</li>" for qi in quality_issues)
        qa_html = f'<h3 style="color:#c00;">Quality Warnings</h3><ul>{qa_items}</ul>'

    tags_str = ", ".join(tags) if tags else ""

    html_body = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: 'Malgun Gothic', sans-serif; max-width: 720px; margin: 0 auto; padding: 20px;">
<div style="background: #f0f4ff; padding: 16px 20px; border-radius: 8px; margin-bottom: 20px;">
    <h1 style="margin: 0 0 8px 0; font-size: 22px; color: #222;">{title}</h1>
    <p style="margin: 0; color: #666; font-size: 13px;">
        Corner: {corner} | Slug: {slug}<br>
        Tags: {tags_str}<br>
        Created: {created_at}
    </p>
</div>
{kp_html}
{qa_html}
<hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">
<div style="line-height: 1.8; font-size: 15px;">
{body}
</div>
<hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">
<p style="color: #999; font-size: 12px;">
    Auto-generated by The 4th Path blog pipeline.
</p>
</body>
</html>"""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"[The 4th Path] {title}"
    msg["From"] = smtp_user
    msg["To"] = recipient
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    try:
        with smtplib.SMTP(smtp_host, smtp_port, timeout=30) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(smtp_user, smtp_password)
            server.sendmail(smtp_user, [recipient], msg.as_string())
        logger.info(f"Email sent: {title} -> {recipient}")
        return True
    except Exception as e:
        logger.error(f"Email send failed: {e}")
        return False
